### ISSUE TITLE
关于判断策略

### ISSUE THREAD

**Issue by JamisonXing** [GalliumWang/standardSitting#8]
大佬你好，我想问下你们的策略是怎么想出来的，那些main.py中的常量0.25、0.13....是怎么得出的，有没有可以参考的论文呢，感谢感谢

**Comment by GalliumWang** [comment]
> 大佬你好，我想问下你们的策略是怎么想出来的，那些main.py中的常量0.25、0.13....是怎么得出的，有没有可以参考的论文呢，感谢感谢

这个是当初班级课程里面的一个项目，各种判断策略也只是大概按照平面几何的角度来计算的QAQ😂

**Comment by JamisonXing** [comment]
okok
